export const FORMULARIO_PROYECTO = "PROYECTO_FORM";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";

export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
